### ISSUE TITLE
Copywriting Request for the project

### ISSUE THREAD

**Issue by princekelly1** [djordjeparovic/steemlookup#1]
Hi i and a friend of mine would like to help contribute to the project by writing The readme file, About Us, Privacy policies and FAQ for this wonderful project.
am princekelly and my friend is ewuoso.
please can we proceed and submit a pull request to be merged?

**Comment by djordjeparovic** [comment]
Hello guys,

Everyone is more than welcome to work on the project and every good contribution will be merged. 
Since most of the pages you are talking about are not defined by Curie yet, we will need to wait a little bit for that. 

Regarding README, I have it already - it will be pushed very soon, so no need to change anything there yet. 

But for the moment, I think you can help with the FAQ page since you are using steemlookup.com for a while, you can work on it. 

I will close this issue, it's here as a reminder to everyone to be free to submit a PR anytime. 

Thanks!
All the best!

**Comment by princekelly1** [comment]
OK I would surely write the FAQ, thanks

**Comment by princekelly1** [comment]
Curie
